// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }







import type { Metadata } from 'next';
import './globals.css';
import ResultsChecker from '../components/ResultChecker';

export const metadata: Metadata = {
  title: 'ExamPortal - Secure Online Examination Platform',
  description: 'A modern, secure, and efficient online examination platform for educational institutions. Take exams with confidence and get instant results.',
  keywords: 'online exam, examination platform, student portal, education technology',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}
        <ResultsChecker />
      </body>
    </html>
  );
}